/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UsersController_findAll_v1"];
        put?: never;
        post: operations["UsersController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UsersController_findOne_v1"];
        put?: never;
        post?: never;
        delete: operations["UsersController_remove_v1"];
        options?: never;
        head?: never;
        patch: operations["UsersController_update_v1"];
        trace?: never;
    };
    "/api/v1/files/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["FilesLocalController_uploadFile_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/email/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_login_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/email/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_register_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/email/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_confirmEmail_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/email/confirm/new": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_confirmNewEmail_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/forgot/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_forgotPassword_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/reset/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_resetPassword_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_me_v1"];
        put?: never;
        post?: never;
        delete: operations["AuthController_delete_v1"];
        options?: never;
        head?: never;
        patch: operations["AuthController_update_v1"];
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_refresh_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_logout_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/brands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["BrandsController_findAll_v1"];
        put?: never;
        post: operations["BrandsController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/brands/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["BrandsController_findOne_v1"];
        put?: never;
        post?: never;
        delete: operations["BrandsController_remove_v1"];
        options?: never;
        head?: never;
        patch: operations["BrandsController_update_v1"];
        trace?: never;
    };
    "/api/v1/brands/{id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["BrandsController_getMembers_v1"];
        put?: never;
        post: operations["BrandsController_addMember_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/brands/{id}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["BrandsController_removeMember_v1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/facebook/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthFacebookController_login_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthGoogleController_login_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/apple/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthAppleController_login_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HomeController_appInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HomeController_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HomeController_ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ConnectionsController_findAll_v1"];
        put?: never;
        post: operations["ConnectionsController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connections/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ConnectionsController_findOne_v1"];
        put?: never;
        post?: never;
        delete: operations["ConnectionsController_remove_v1"];
        options?: never;
        head?: never;
        patch: operations["ConnectionsController_update_v1"];
        trace?: never;
    };
    "/api/v1/connections/{id}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ConnectionsController_sync_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/social/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AnalyticsController_getSocialOverview_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/social/top-posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AnalyticsController_getTopPosts_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/social/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AnalyticsController_getSocialSummary_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        FileDto: {
            id: string;
        };
        RoleDto: {
            id: Record<string, never>;
        };
        StatusDto: {
            id: Record<string, never>;
        };
        CreateUserDto: {
            /** @example test1@example.com */
            email: string;
            password: string;
            /** @example John */
            firstName: string;
            /** @example Doe */
            lastName: string;
            photo?: components["schemas"]["FileDto"];
            role?: components["schemas"]["RoleDto"];
            status?: components["schemas"]["StatusDto"];
        };
        FileType: {
            /** @example cbcfa8b8-3a25-4adb-a9c6-e325f0d0f3ae */
            id: string;
            /** @example https://example.com/path/to/file.jpg */
            path: string;
        };
        Role: {
            id: number;
            /** @example admin */
            name: string;
        };
        Status: {
            id: number;
            /** @example active */
            name: string;
        };
        User: {
            id: number;
            /** @example john.doe@example.com */
            email: string;
            /** @example email */
            provider: string;
            /** @example 1234567890 */
            socialId: string;
            /** @example John */
            firstName: string;
            /** @example Doe */
            lastName: string;
            photo: components["schemas"]["FileType"];
            role: components["schemas"]["Role"];
            status: components["schemas"]["Status"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            deletedAt: string;
        };
        InfinityPaginationUserResponseDto: {
            data: components["schemas"]["User"][];
            /** @example true */
            hasNextPage: boolean;
        };
        UpdateUserDto: {
            /** @example test1@example.com */
            email?: string;
            password?: string;
            /** @example John */
            firstName?: string;
            /** @example Doe */
            lastName?: string;
            photo?: components["schemas"]["FileDto"];
            role?: components["schemas"]["RoleDto"];
            status?: components["schemas"]["StatusDto"];
        };
        FileResponseDto: {
            file: components["schemas"]["FileType"];
        };
        AuthEmailLoginDto: {
            /** @example test1@example.com */
            email: string;
            password: string;
        };
        LoginResponseDto: {
            token: string;
            refreshToken: string;
            tokenExpires: number;
            user: components["schemas"]["User"];
        };
        AuthRegisterLoginDto: {
            /** @example test1@example.com */
            email: string;
            password: string;
            /** @example John */
            firstName: string;
            /** @example Doe */
            lastName: string;
        };
        AuthConfirmEmailDto: {
            hash: string;
        };
        AuthForgotPasswordDto: {
            /** @example test1@example.com */
            email: string;
        };
        AuthResetPasswordDto: {
            password: string;
            hash: string;
        };
        RefreshResponseDto: {
            token: string;
            refreshToken: string;
            tokenExpires: number;
        };
        AuthUpdateDto: {
            photo?: components["schemas"]["FileDto"];
            /** @example John */
            firstName?: string;
            /** @example Doe */
            lastName?: string;
            /** @example new.email@example.com */
            email?: string;
            password?: string;
            oldPassword?: string;
        };
        CreateBrandDto: {
            /** @example Acme Bolivia */
            name: string;
            /** @example acme-bolivia */
            slug: string;
            /** @example Empresa líder en Bolivia */
            description?: string;
            /** @default true */
            isActive: boolean;
        };
        UpdateBrandDto: {
            /** @example Acme Bolivia */
            name?: string;
            /** @example acme-bolivia */
            slug?: string;
            /** @example Empresa líder en Bolivia */
            description?: string;
            /** @default true */
            isActive: boolean;
        };
        AddMemberDto: {
            /** @example 1 */
            userId: number;
            /**
             * @default member
             * @enum {string}
             */
            role: "admin" | "member" | "client";
        };
        AuthFacebookLoginDto: {
            /** @example abc */
            accessToken: string;
        };
        AuthGoogleLoginDto: {
            /** @example abc */
            idToken: string;
        };
        AuthAppleLoginDto: {
            /** @example abc */
            idToken: string;
            firstName?: string;
            lastName?: string;
        };
        CreateConnectionDto: {
            /** @enum {string} */
            channel: "facebook_page" | "instagram" | "tiktok" | "linkedin" | "youtube" | "google_ads" | "ga4";
            accountHandle: string;
            accountId: string;
            accessToken: string;
            refreshToken?: string;
            expiresAt?: string;
            scopes?: string[];
            metadata?: Record<string, never>;
        };
        UpdateConnectionDto: {
            /** @enum {string} */
            channel?: "facebook_page" | "instagram" | "tiktok" | "linkedin" | "youtube" | "google_ads" | "ga4";
            accountHandle?: string;
            accountId?: string;
            accessToken?: string;
            refreshToken?: string;
            expiresAt?: string;
            scopes?: string[];
            metadata?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    UsersController_findAll_v1: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                filters?: string;
                sort?: string;
            };
            header?: {
                "x-custom-lang"?: unknown;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InfinityPaginationUserResponseDto"];
                };
            };
        };
    };
    UsersController_create_v1: {
        parameters: {
            query?: never;
            header?: {
                "x-custom-lang"?: unknown;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    UsersController_findOne_v1: {
        parameters: {
            query?: never;
            header?: {
                "x-custom-lang"?: unknown;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    UsersController_remove_v1: {
        parameters: {
            query?: never;
            header?: {
                "x-custom-lang"?: unknown;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_update_v1: {
        parameters: {
            query?: never;
            header?: {
                "x-custom-lang"?: unknown;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    FilesLocalController_uploadFile_v1: {
        parameters: {
            query?: never;
            header?: {
                "x-custom-lang"?: unknown;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file?: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileResponseDto"];
                };
            };
        };
    };
    AuthController_login_v1: {
        parameters: {
            query?: never;
            header?: {
                "x-custom-lang"?: unknown;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthEmailLoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponseDto"];
                };
            };
        };
    };
    AuthController_register_v1: {
        parameters: {
            query?: never;
            header?: {
                "x-custom-lang"?: unknown;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthRegisterLoginDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_confirmEmail_v1: {
        parameters: {
            query?: never;
            header?: {
                "x-custom-lang"?: unknown;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthConfirmEmailDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_confirmNewEmail_v1: {
        parameters: {
            query?: never;
            header?: {
                "x-custom-lang"?: unknown;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthConfirmEmailDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_forgotPassword_v1: {
        parameters: {
            query?: never;
            header?: {
                "x-custom-lang"?: unknown;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthForgotPasswordDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_resetPassword_v1: {
        parameters: {
            query?: never;
            header?: {
                "x-custom-lang"?: unknown;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthResetPasswordDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me_v1: {
        parameters: {
            query?: never;
            header?: {
                "x-custom-lang"?: unknown;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    AuthController_delete_v1: {
        parameters: {
            query?: never;
            header?: {
                "x-custom-lang"?: unknown;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_update_v1: {
        parameters: {
            query?: never;
            header?: {
                "x-custom-lang"?: unknown;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthUpdateDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    AuthController_refresh_v1: {
        parameters: {
            query?: never;
            header?: {
                "x-custom-lang"?: unknown;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResponseDto"];
                };
            };
        };
    };
    AuthController_logout_v1: {
        parameters: {
            query?: never;
            header?: {
                "x-custom-lang"?: unknown;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BrandsController_findAll_v1: {
        parameters: {
            query?: never;
            header?: {
                "x-custom-lang"?: unknown;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BrandsController_create_v1: {
        parameters: {
            query?: never;
            header?: {
                "x-custom-lang"?: unknown;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBrandDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BrandsController_findOne_v1: {
        parameters: {
            query?: never;
            header?: {
                "x-custom-lang"?: unknown;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BrandsController_remove_v1: {
        parameters: {
            query?: never;
            header?: {
                "x-custom-lang"?: unknown;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BrandsController_update_v1: {
        parameters: {
            query?: never;
            header?: {
                "x-custom-lang"?: unknown;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBrandDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BrandsController_getMembers_v1: {
        parameters: {
            query?: never;
            header?: {
                "x-custom-lang"?: unknown;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BrandsController_addMember_v1: {
        parameters: {
            query?: never;
            header?: {
                "x-custom-lang"?: unknown;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddMemberDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BrandsController_removeMember_v1: {
        parameters: {
            query?: never;
            header?: {
                "x-custom-lang"?: unknown;
            };
            path: {
                id: number;
                userId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthFacebookController_login_v1: {
        parameters: {
            query?: never;
            header?: {
                "x-custom-lang"?: unknown;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthFacebookLoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponseDto"];
                };
            };
        };
    };
    AuthGoogleController_login_v1: {
        parameters: {
            query?: never;
            header?: {
                "x-custom-lang"?: unknown;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthGoogleLoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponseDto"];
                };
            };
        };
    };
    AuthAppleController_login_v1: {
        parameters: {
            query?: never;
            header?: {
                "x-custom-lang"?: unknown;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthAppleLoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponseDto"];
                };
            };
        };
    };
    HomeController_appInfo: {
        parameters: {
            query?: never;
            header?: {
                "x-custom-lang"?: unknown;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HomeController_health: {
        parameters: {
            query?: never;
            header?: {
                "x-custom-lang"?: unknown;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HomeController_ready: {
        parameters: {
            query?: never;
            header?: {
                "x-custom-lang"?: unknown;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ConnectionsController_findAll_v1: {
        parameters: {
            query?: never;
            header: {
                "x-brand-id": string;
                "x-custom-lang"?: unknown;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ConnectionsController_create_v1: {
        parameters: {
            query?: never;
            header: {
                "x-brand-id": string;
                "x-custom-lang"?: unknown;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateConnectionDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ConnectionsController_findOne_v1: {
        parameters: {
            query?: never;
            header: {
                "x-brand-id": string;
                "x-custom-lang"?: unknown;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ConnectionsController_remove_v1: {
        parameters: {
            query?: never;
            header: {
                "x-brand-id": string;
                "x-custom-lang"?: unknown;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ConnectionsController_update_v1: {
        parameters: {
            query?: never;
            header: {
                "x-brand-id": string;
                "x-custom-lang"?: unknown;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateConnectionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ConnectionsController_sync_v1: {
        parameters: {
            query?: never;
            header: {
                "x-brand-id": string;
                "x-custom-lang"?: unknown;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AnalyticsController_getSocialOverview_v1: {
        parameters: {
            query: {
                connectionId: number;
                from: string;
                to: string;
            };
            header: {
                "x-brand-id": string;
                "x-custom-lang"?: unknown;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AnalyticsController_getTopPosts_v1: {
        parameters: {
            query: {
                connectionId: number;
                limit?: number;
            };
            header: {
                "x-brand-id": string;
                "x-custom-lang"?: unknown;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AnalyticsController_getSocialSummary_v1: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header: {
                "x-brand-id": string;
                "x-custom-lang"?: unknown;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
